### ISSUE TITLE
Insecure response error

### ISSUE THREAD

**Issue by jameschambers** [schovi/webpack-chrome-extension#12]
I'm seeing this error in the console when navigating to any page: 

`Failed to load resource: net::ERR_INSECURE_RESPONSE https://localhost:3001/app/index.js` 

Steps to reproduce: 
1. `npm install && gulp` 
2. Load extension from `/build/` folder 
3. Open console or inspect background view

**Comment by dmwyatt** [comment]
Yeah, I'm also getting this.  Chrome 46 on Ubuntu 14.04.  A short bit of googling made me try starting chrome with `--ignore-certificate-errors`, but that didn't fix it.

**Comment by kfei** [comment]
+1
I got this issue on both Chrome 46.0.2490 and Chromium 44.0.2403.0

**Comment by schovi** [comment]
You can pick that link `https://localhost:3001/app/index.js` open it directly in browser and accept Error page with warning about insecure page. Then all requests will be fine.

This is https://www.npmjs.com/package/http-server related "error"
