### ISSUE TITLE
Cannot access chrome API on background

### ISSUE THREAD

**Issue by tennisonchan** [schovi/webpack-chrome-extension#16]
Due to the structure on background, it cannot access important chrome API like `chrome.runtime.onConnect` on any file calling via `localhost:3001`.

https://developer.chrome.com/extensions/runtime#event-onConnect

**Comment by tennisonchan** [comment]
Sorry. It seems like an issue related to Chrome or something else. Closing it now.

**Comment by edanweis** [comment]
@tennisonchan Did you resolve this issue? I have the same problem on Windows Chrome v50. Works fine on Chrome Linux.
