### ISSUE TITLE
error: ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by freeslugs** [schovi/webpack-chrome-extension#22]
1. `npm install`
2. `npm run dev`
3. load unpack extension from `build` folder
4. inspect background page: `https://localhost:3001/background/index.js Failed to load resource: net::ERR_INSECURE_RESPONSE`

**Comment by freeslugs** [comment]
Nevermind! All i had to do was visit localhost in a new window and click "proceed anyway" :smile:

**Comment by rkhayat** [comment]
Getting this on several different machines / OS.

**Comment by schovi** [comment]
@freeslugs Gonna add it to README :)
