### ISSUE TITLE
Do not understand Step 5 in "How to run development environment"

### ISSUE THREAD

**Issue by CasperHK** [schovi/webpack-chrome-extension#26]
Firstly, I have run the command `npm install` and get the node_module in the folder.
After step 4, the `Browse For Folder` small window appears, and do not know what path I should use in the textfield of Folder.

```
 5. add REPOSITORY_DIRECTORY/build
```

I guess that `REPOSITORY_DIRECTORY` is `schovi/webpack-chrome-extension`. But I cannot find the `build` folder there. What should I do?

Thank you.

**Comment by schovi** [comment]
@CasperHK you mistake point 1, where is `npm start` and not `npm install`. `start` starts whole building process and creates `build` directory, but `install` is prerequisite command.
