### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ladas-larry** [schovi/webpack-chrome-extension#3]
Could you add some comments about how webpack configuration works. I want to add Popup and I'm not very sure how.

**Comment by schovi** [comment]
https://github.com/schovi/webpack-chrome-extension/commit/18b6674459b25d2866e053c5376aba707c2e0b6b

@Dharmoslap I clean and add some texts into webpack.generator.js More improvement will come :)
What is "Popup" I can help you there.

**Comment by ladas-larry** [comment]
https://developer.chrome.com/extensions/browserAction#popups

**Comment by schovi** [comment]
@Dharmoslap I made experimental implementation with Popup https://github.com/schovi/webpack-chrome-extension/commit/5329cb0f4e189f8b4b6ce152b35fa1d5c6d5171c
You can import any js or styles to `src/my_popup_menu.js` and use them in popup.
File `src/my_popup_menu.html` is included into body of generated html layout.

**Comment by ladas-larry** [comment]
Thanks
