### ISSUE TITLE
Strip out less, stylus, sass loaders

### ISSUE THREAD

**Issue by sergey-lapin** [schovi/webpack-chrome-extension#4]
First of all, big thanks to you for this contribution, great work!

Not all devs use these loaders and mostly not use them all at once. sass loader also require node-gyp step so I already encountered some problems on windows. I guess cool solution for this - make some webpack.config hook for user, so he could override configuration.

Like search for some webpack.chrome-extension.config,js file in the root of user project and merge it then with default config.

**Comment by sergey-lapin** [comment]
Also this project is more like seed now, but if we strip out all extra stuff and leave some core that could be installed from npm, we can cover it with tests, linting add travis support.

**Comment by schovi** [comment]
@lapanoid thanks for positive feedback. It is little bit old version for me. We are working on project and it is under heavy development :) I am little out of time now, but as soon as possible i will commit update with everything and then we can make cuts and sharp it.

Any suggestions or pull requests are welcome.

**Comment by schovi** [comment]
@lapanoid I made some cleaning, refactoring, commenting.

https://github.com/schovi/webpack-chrome-extension/commit/355a2aa2200fc44371b1851398c25462f9328937
https://github.com/schovi/webpack-chrome-extension/commit/57927db13c71d427f40f28b6ca2fbdd7e7008a4b
https://github.com/schovi/webpack-chrome-extension/commit/041dd9791c66954a930baa6bd881a8eac326f5f2
https://github.com/schovi/webpack-chrome-extension/commit/4b26d8a17ce533f0cc516ea220e1e15e02edc2cc
https://github.com/schovi/webpack-chrome-extension/commit/1827b14e598ac87346f9c8d189c6eaadeb48a8ac
https://github.com/schovi/webpack-chrome-extension/commit/9978c68a914470327ee40ffb52040c108212280e

Any more suggesting? My plan for now is to improve README file.

**Comment by sergey-lapin** [comment]
That is great! At least this issue should be closed now. Would be great if you write about how it works underhood.

**Comment by schovi** [comment]
I will try :)

**Comment by schovi** [comment]
I will try
