### ISSUE TITLE
Can we change devServer setting to https ?

### ISSUE THREAD

**Issue by hungtuchen** [schovi/webpack-chrome-extension#5]
As title described,
I tried adding `https: true` in `dev-env/webpack.server.js` and
 change every occurrence of `http` to `https` , but can't work out as expected,
(I have to let chrome explicit access to `https://localhost:3001/content.js`)
If I can't change that setting, then I can't let `content.js` works in 
ex: `https://facebook.com` and almost most of the site.
Do we have a better solution for this, since development for most of the site that is https based 
is a non-trivial thing.

**Comment by schovi** [comment]
Thanks for feedback,

After some digging I figured out how to do that. Commit https://github.com/schovi/webpack-chrome-extension/commit/f62a616d4461345a2ee53bbfbb92613bd54fda03

HTTPS as default is better, but I will make some config to allow change protocol, host, port and other webpack properties.

**Comment by schovi** [comment]
One more fix in making manifest.json https://github.com/schovi/webpack-chrome-extension/commit/57927db13c71d427f40f28b6ca2fbdd7e7008a4b#diff-d202225ac87f27a10bf4a0f7e469305aR44
setting property content_script_policy was not correct
