### ISSUE TITLE
Is page_action not supported?

### ISSUE THREAD

**Issue by hungtuchen** [schovi/webpack-chrome-extension#6]
Hi, thanks for the quick response to #5 , it works great?
one to thing to bother, when I tried replacing `browser_action` with `page_action`
and in background script, I let `if url == ....`, then `chrome.pageAction.show....`
but I found that if I change `browser_action` to `page_action`, `popup/index.html` will be compiled into `build`, is that intentional, how can I config that?

**Comment by schovi** [comment]
Thanks for another feedback.
I add features as I personaly need them and as I explore how chrome extensions works.
Here is fix for you with simple usage of page action (adding icon and showing on each page)

https://github.com/schovi/webpack-chrome-extension/commit/46281c2e647c28c18494d3c2f97eaf9a7daf7905
