### ISSUE TITLE
webpack-prod vs webpack-dev

### ISSUE THREAD

**Issue by rstormsf** [schovi/webpack-chrome-extension#8]
those 2 tasks are completely the same in gulpfile

https://github.com/schovi/webpack-chrome-extension/blob/master/gulpfile.babel.js#L37-L39
https://github.com/schovi/webpack-chrome-extension/blob/master/gulpfile.babel.js#L45-L47

**Comment by schovi** [comment]
One have `true` as first argument for function `configGenerator` and another `false` :)

**Comment by rstormsf** [comment]
Ohhhh, too many hours in front of monitor. :-) 
Sorry about that
