### ISSUE TITLE
production build doesn't work

### ISSUE THREAD

**Issue by rstormsf** [schovi/webpack-chrome-extension#9]
chrome-extension://sdfsdff/newtab/newtab/index.js Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by schovi** [comment]
Do you have public repo with that? Problem is obvious, but why it happened is another story :)

**Comment by rstormsf** [comment]
`gulp -p` and install it, I've tried to figure it out, :-( no luck.

**Comment by MattSPalmer** [comment]
See my pull request (#10), should address the issue. The relative path to index.js is currently incorrect in production builds.

**Comment by schovi** [comment]
Thanks to @MattSPalmer, we find the source of issue. Fixed with commit https://github.com/schovi/webpack-chrome-extension/commit/9ffe78cf13028b5d88e8442e3e8e1995856c6f62
